image: python:3

before_script:
  - pip install -r requirements.txt

#services:
#  - postgres

lint:
  before_script:
    - pip install flake8
  script:
    - flake8

# deploy:
#   before_script:
#   script:
#     - git push heroku master
