image: python:3
stages:
  - lint
  - test
  - deploy

before_script:
  - pip install -r requirements.txt

services:
  - postgres

lint:
  before_script:
    - pip install flake8
  script:
    - flake8

test:
  script:
    - python manage.py test

deploy:
  image:
  before_script:
  script:
    - git remote add heroku https://git.heroku.com/riskofrain2wiki.git
    - git push heroku master
  only:
  - master
