image: python:3
stages:
  - lint
  - test
  - deploy

before_script:
  - pip install -r requirements.txt

#services:
#  - postgres

lint:
  before_script:
    - pip install flake8
  script:
    - flake8

test:
  script:
    - python manage.py test

deploy:
  before_script:
  script:
    - git push heroku master
  only:
  - master
